export const ShopData = [
  {
    id: 1,
    sku: 123456789104,
    title: "sphynx tie day grey shirt",
    quantity: 19,
    description: "sphynx tie day grey",
    availableSize: ["X", "L", "XL"],
    price: 150,
    isFreeShopping: false,
    key: 1,
  },
  {
    id: 2,
    sku: 123456789103,
    title: "sphynx tie day grey ",
    quantity: 10,
    description: "sphynx tie day grey",
    availableSize: ["X", "XL", "XXL"],
    price: 100,
    isFreeShopping: true,
    key: 2,
  },
  {
    id: 3,
    sku: 123456789102,
    title: "danger tie day grey t-shirt",
    quantity: 1,
    description: "sphynx tie day grey",
    availableSize: ["X", "L", "XL"],
    price: 110,
    isFreeShopping: true,
    key: 3,
  },
  {
    id: 4,
    sku: 123456789101,
    title: "scarf tie day grey t-shirt",
    quantity: 4,
    description: "sphynx tie day grey",
    availableSize: ["X", "L"],
    price: 70,
    isFreeShopping: false,
    key: 4,
  },
  {
    id: 5,
    sku: 1234567891,
    title: "sphynx knife day grey t-shirt",
    quantity: 6,
    description: "sphynx tie day grey",
    availableSize: ["XL", "XXL"],
    price: 160,
    isFreeShopping: true,
    key: 5,
  },
];
