export const ShopData = [
  {
    id: 1,
    sku: 123456789104,
    title: "green shirt",
    quantity: 19,
    description: "sphynx tie day grey",
    availableSize: ["X", "L", "XL"],
    price: 150,
    isFreeShopping: false,
    key: 1,
  },
  {
    id: 2,
    sku: 123456789103,
    title: "blue shirt",
    quantity: 10,
    description: "sphynx tie day grey",
    availableSize: ["X", "XL", "XXL"],
    price: 100,
    isFreeShopping: true,
    key: 2,
  },
  {
    id: 3,
    sku: 123456789102,
    title: "red shirt",
    quantity: 1,
    description: "sphynx tie day grey",
    availableSize: ["X", "L", "XL"],
    price: 110,
    isFreeShopping: true,
    key: 3,
  },
  {
    id: 4,
    sku: 123456789101,
    title: "white shirt",
    quantity: 4,
    description: "sphynx tie day grey",
    availableSize: ["X", "L"],
    price: 70,
    isFreeShopping: false,
    key: 4,
  },
  {
    id: 5,
    sku: 1234567891,
    title: "black shirt",
    quantity: 6,
    description: "sphynx tie day grey",
    availableSize: ["XL", "XXL", "S"],
    price: 160,
    isFreeShopping: true,
    key: 5,
  },
];
export const sizeObject = [
  { name: "All", value: "All" },
  { name: "S", value: "S" },
  { name: "L", value: "L" },
  { name: "X", value: "X" },
  { name: "XL", value: "XL" },
  { name: "XXl", value: "XXL" },
];
export const priceSort = [
  { name: "Defualt", value: "Defualt" },
  { name: "Highest", value: "Highest" },
  { name: "Lowest", value: "Lowest" },
];
export const shopItemLength = ShopData.length;
